name: integration

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Pull Docker Image
      run: docker pull linkacloud/d2vm:latest

    - name: Compile init
      run: gcc -Wall -o init -static init.c

    - name: Build Dockerfile as VM image
      run: docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock --privileged -v $PWD:/d2vm -w /d2vm linkacloud/d2vm:latest build --file python.Dockerfile --output python.qcow2 .

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: python.qcow2
        path: python.qcow2
